### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by bimlas** [tsertkov/exec-sh#11]
I just want to thank you for this great product! 4.5M weekly downloads and still only 31 stars ?! :( Much more attention should be paid to the repository by the users.

**Comment by tsertkov** [comment]
Thanks for the kind words @bimlas !

Perhaps this module is too simple to deserve a star :) In fact I believe most of the downloads are coming from https://www.npmjs.com/package/watch which depends on `exec-sh` and has comparable number of weekly downloads.
