### ISSUE TITLE
Update merge dependency

### ISSUE THREAD

**Issue by sami-eljabali** [tsertkov/exec-sh#32]
Hitting a security issue:

`Prototype Pollution in merge`
```
watch@1.0.2 requires merge@^1.2.0 via exec-sh@0.2.2
No patched version available for merge
```

Is it possible to update to latest merge?

Thanks!

**Comment by tsertkov** [comment]
Please update to the latest version of exec-sh v0.4.0 which has 0 dependencies.
See https://github.com/tsertkov/exec-sh/commit/933cc023a1e84ef7140bd215c106503edcd60866
